export const environment = {
  production: true,
  API_ENPOINT: 'https://exchangecurrencyapp-dp-render.onrender.com/api',
  NG_API_KEY: '',
  CURRENCIES_URL: '/currencies',
  LOCATIONS_URL: '/currencies/locations',
  EXCHANGE_URL: '/exchange',
  API_KEY_ATTRIBUTE: 'apiKey=',
  START_DATE_ATTRIBUTE: 'startDate=',
  FINISH_DATE_ATTRIBUTE: 'finishDate=',
  BASE_CURRENCY_ATTRIBUTE: 'baseCurrency=',
  REQUESTED_CURRENCY_ATTRIBUTE: 'currency=',
  DEFAULT_BASE_CURRENCY: 'EUR',
  DEFAULT_REQUESTED_CURRENCY: 'EUR',
  CURRENCY_DATE_ATTRIBUTE: 'date=',
};
